// Generated by dts-bundle-generator v5.6.0

declare const _default: {
	readonly numOfBlocks: 8;
	readonly blockDia: 2;
	readonly gameWindow: {
		readonly width: 800;
		readonly height: 800;
	};
};
export default _default;

export {};
