// Generated by dts-bundle-generator v5.6.0

declare const _default: {
	readonly numOfBlocks: 8;
	readonly blockDia: 4;
	readonly mapDia: 1500;
	readonly gameWindow: {
		readonly width: 1600;
		readonly height: 1600;
	};
};
export default _default;

export {};
