// Generated by dts-bundle-generator v5.6.0

declare const _default: {
	readonly numOfBlocks: 5;
	readonly blockDia: 16;
	readonly mapDimensions: {
		readonly width: 400;
		readonly height: 400;
	};
};
export default _default;

export {};
